name: Akiba
description: "Your Personal Financial Planner"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  lottie: ^3.3.1
  smooth_page_indicator: ^1.2.0+3
  fl_chart: ^0.70.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.14
  intl: ^0.19.0
  uuid: ^4.5.1
  percent_indicator: ^4.2.4
  flutter_local_notifications: ^18.0.1 
  flutter_riverpod: ^2.6.1
  local_auth: ^2.3.0
  flutter_animate: ^4.5.2
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  pdf: ^3.11.2
  share_plus: ^10.1.4
  printing: ^5.14.2
  device_info_plus: ^11.3.0
  flutter_launcher_icons: ^0.14.3
  emoji_picker_flutter: ^4.3.0
  timezone: ^0.10.0
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_localization: ^0.3.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/
    - assets/savings.json
    - assets/money_growth.json
    - assets/icon.png
    - assets/fonts/

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
    - family: NotoSansSymbols
      fonts:
        - asset: assets/fonts/NotoSansSymbols-Regular.ttf
    - family: NotoColorEmoji
      fonts:
        - asset: assets/fonts/NotoColorEmoji-Regular.ttf

  uses-material-design: true

flutter_launcher_icons:
  image_path: 'assets/icon.png'
  android: true
  ios: true
